Repository IsyFact/isy-github-actions-templates, pull requests merged in 2024-08, with the labels that each got.

#14 IFS-3611: Fixing syntax error in PR Agent
  .github/workflows/pr_agent.yml
  .github/workflows/update_antora_version.yml
  ORT Reports/antora.yml
Labels: bug fix, configuration changes, Review effort [1-5]: 2

#17 IFS-3938: Fixed whitespace error when checking release existence
  .github/workflows/maven_deploy_template.yml
  CHANGELOG.md
Labels: Review effort [1-5]: 1, documentation, bug_fix

#15 feat: IFS-3956: changed destination branch
  .github/workflows/oss_review_toolkit_template.yml
  CHANGELOG.md
  ORT Reports/antora.yml
  ORT Reports/modules/ROOT/nav.adoc
  ORT Reports/modules/ROOT/pages/isy-github-actions-templates/AsciiDoc_cve_summary_report_template.adoc
  ORT Reports/modules/ROOT/pages/isy-github-actions-templates/reports.adoc
  README.adoc
Labels: configuration changes, enhancement, Review effort [1-5]: 1

#18 ci: Default deploy url for Deploy Maven Template
  .github/workflows/maven_deploy_template.yml
  CHANGELOG.md
  README.adoc
Labels: enhancement, Review effort [1-5]: 1

#19 IFS-3956: Enhanced ORT workflow with PR automation and secret configuration
  .github/workflows/oss_review_toolkit_template.yml
Labels: configuration changes, Review effort [1-5]: 2, enhancement

#26 IFS-3956: OSS Review Toolkit
  .github/workflows/oss_review_toolkit_template.yml
Labels: Review effort [1-5]: 2, enhancement
